{{- with .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name | default .host }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
    {{- with .labels }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .class | default "nginx" }}
    {{- with .annotations }}{{- toYaml . | nindent 4 }}{{- end }}
spec:
  rules:
  {{- range .hosts }}
    -
      host: {{ include "helpers.tplvalues.render" (dict "value" .host "context" $) }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ default "/" .path }}
          pathType: {{ default "Prefix" .pathType }}
          backend:
            {{- include "helpers.ingress.backend" (dict "serviceName" .serviceName "servicePort" .servicePort "context" $) | nindent 12 }}
        {{- end }}
  {{- end }}
  {{- with .tls }}
  tls:
    - secretName: {{ .secretName }}
  {{- end }}
{{- end }}