{{- range .Values.secrets -}}
{{- if not (eq .name "secret-envs") }}
---
apiVersion: v1
kind: Secret
type: {{ .type | default  "Opaque" }}
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
  annotations:
    {{- include "helpers.app.hooksAnnotations" $ | nindent 4 }}
    {{- with .annotations }}{{- include "helpers.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}{{ end }}
data:
  {{- include "helpers.secrets.render" (dict "value" .data) | indent 2 }}
{{- end }}
{{- end }}