{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
{{- if .labels }}
  labels:
{{ toYaml .labels | indent 4 }}
{{- end }}
provisioner: {{ .provisioner }}
parameters: {{ .parameters | default (dict) | toYaml | nindent 2 }}
volumeBindingMode: {{ .volumeBindingMode }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- if .allowedTopologies }}
allowedTopologies:
{{ toYaml .allowedTopologies | indent 2 }}
{{- end }}
{{- end }}