{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
provisioner: {{ .provisioner }}
volumeBindingMode: {{ .volumeBindingMode }}
reclaimPolicy: {{ .reclaimPolicy }}
{{- if .allowedTopologies }}
allowedTopologies:
{{ toYaml .allowedTopologies | indent 2 }}
{{- end }}
{{- end }}