{{- range .Values.vaultSecrets }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  # Name of the kubernetes secret to be created
  name: {{ .name }}
spec:
  type: {{ .type | default "Opaque" }}
  path: {{ .path }}
{{- if .templates }}
  templates:
  {{- range $key, $value := .templates }}
    {{ $key | upper }}: {{ $value | squote }}
  {{- end }}
{{- end}}
{{- end }}